// <auto-generated />
using System;
using CongestionTaxCalculator.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CongestionTaxCalculator.Infrastructure.Migrations
{
    [DbContext(typeof(CongestionTaxDbContext))]
    [Migration("20251102123217_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsDayBeforeHolidayTaxExempt")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHolidayTaxExempt")
                        .HasColumnType("bit");

                    b.Property<bool>("IsJulyTaxExempt")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWeekendTaxExempt")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SingleChargeDurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("SingleChargeDurationMinutes");

                    b.HasKey("Id");

                    b.ToTable("Cities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 130, DateTimeKind.Utc).AddTicks(6076),
                            IsDayBeforeHolidayTaxExempt = true,
                            IsHolidayTaxExempt = true,
                            IsJulyTaxExempt = true,
                            IsWeekendTaxExempt = true,
                            Name = "Gothenburg",
                            SingleChargeDurationMinutes = 60
                        });
                });

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Holidays", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 130, DateTimeKind.Utc).AddTicks(9814),
                            Date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "New Year’s Day"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 130, DateTimeKind.Utc).AddTicks(9817),
                            Date = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Christmas Day"
                        });
                });

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.TaxExemptVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("TaxExemptVehicles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 131, DateTimeKind.Utc).AddTicks(1881),
                            VehicleType = 4
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 131, DateTimeKind.Utc).AddTicks(1882),
                            VehicleType = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 131, DateTimeKind.Utc).AddTicks(1883),
                            VehicleType = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 131, DateTimeKind.Utc).AddTicks(1884),
                            VehicleType = 5
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 131, DateTimeKind.Utc).AddTicks(1885),
                            VehicleType = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 131, DateTimeKind.Utc).AddTicks(1885),
                            VehicleType = 6
                        });
                });

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.TaxRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("TaxRules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 135, DateTimeKind.Utc).AddTicks(2881),
                            EndTime = new TimeSpan(0, 6, 30, 0, 0),
                            StartTime = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 135, DateTimeKind.Utc).AddTicks(2884),
                            EndTime = new TimeSpan(0, 7, 0, 0, 0),
                            StartTime = new TimeSpan(0, 6, 30, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 135, DateTimeKind.Utc).AddTicks(2886),
                            EndTime = new TimeSpan(0, 8, 0, 0, 0),
                            StartTime = new TimeSpan(0, 7, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.TollPassage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PassageTime")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PassageTime");

                    b.HasIndex("VehicleId");

                    b.HasIndex("CityId", "PassageTime");

                    b.ToTable("TollPassages", (string)null);
                });

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.City", b =>
                {
                    b.OwnsOne("CongestionTaxCalculator.Domain.ValueObjects.Money", "MaximumTaxPerDay", b1 =>
                        {
                            b1.Property<int>("CityId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("MaximumTaxPerDayAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("MaximumTaxPerDayCurrency");

                            b1.HasKey("CityId");

                            b1.ToTable("Cities");

                            b1.WithOwner()
                                .HasForeignKey("CityId");
                        });

                    b.Navigation("MaximumTaxPerDay")
                        .IsRequired();
                });

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.Holiday", b =>
                {
                    b.HasOne("CongestionTaxCalculator.Domain.Entities.City", null)
                        .WithMany("Holidays")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.TaxExemptVehicle", b =>
                {
                    b.HasOne("CongestionTaxCalculator.Domain.Entities.City", null)
                        .WithMany("TaxExemptVehicles")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.TaxRule", b =>
                {
                    b.HasOne("CongestionTaxCalculator.Domain.Entities.City", null)
                        .WithMany("TaxRules")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("CongestionTaxCalculator.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<int>("TaxRuleId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("AmountValue");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("AmountCurrency");

                            b1.HasKey("TaxRuleId");

                            b1.ToTable("TaxRules");

                            b1.WithOwner()
                                .HasForeignKey("TaxRuleId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.TollPassage", b =>
                {
                    b.HasOne("CongestionTaxCalculator.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CongestionTaxCalculator.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CongestionTaxCalculator.Domain.ValueObjects.Money", "AppliedTax", b1 =>
                        {
                            b1.Property<Guid>("TollPassageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("AppliedTax_Amount");

                            b1.Property<string>("Currency")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("AppliedTax_Currency");

                            b1.HasKey("TollPassageId");

                            b1.ToTable("TollPassages");

                            b1.WithOwner()
                                .HasForeignKey("TollPassageId");
                        });

                    b.Navigation("AppliedTax");

                    b.Navigation("City");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.City", b =>
                {
                    b.Navigation("Holidays");

                    b.Navigation("TaxExemptVehicles");

                    b.Navigation("TaxRules");
                });
#pragma warning restore 612, 618
        }
    }
}
