// <auto-generated />
using System;
using CongestionTaxCalculator.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CongestionTaxCalculator.Infrastructure.Migrations
{
    [DbContext(typeof(CongestionTaxDbContext))]
    partial class CongestionTaxDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsDayBeforeHolidayTaxExempt")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHolidayTaxExempt")
                        .HasColumnType("bit");

                    b.Property<bool>("IsJulyTaxExempt")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWeekendTaxExempt")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SingleChargeDurationMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 0, DateTimeKind.Utc),
                            IsDayBeforeHolidayTaxExempt = true,
                            IsHolidayTaxExempt = true,
                            IsJulyTaxExempt = true,
                            IsWeekendTaxExempt = true,
                            Name = "Gothenburg",
                            RowVersion = new byte[] { 145, 236, 2, 68, 100, 140, 29, 69, 187, 161, 174, 97, 61, 189, 123, 86 },
                            SingleChargeDurationMinutes = 60
                        });
                });

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Holidays", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 0, DateTimeKind.Utc),
                            Date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "New Year’s Day",
                            RowVersion = new byte[] { 170, 181, 177, 190, 18, 230, 192, 74, 169, 27, 152, 77, 127, 228, 231, 85 }
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 0, DateTimeKind.Utc),
                            Date = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Christmas Day",
                            RowVersion = new byte[] { 168, 76, 212, 210, 51, 20, 188, 70, 140, 110, 61, 21, 79, 16, 49, 201 }
                        });
                });

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.TaxExemptVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("VehicleId");

                    b.ToTable("TaxExemptVehicles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 0, DateTimeKind.Utc),
                            RowVersion = new byte[] { 60, 186, 144, 32, 209, 198, 119, 65, 130, 225, 209, 223, 246, 168, 95, 217 },
                            VehicleId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 0, DateTimeKind.Utc),
                            RowVersion = new byte[] { 63, 79, 20, 135, 166, 52, 4, 71, 143, 160, 36, 213, 7, 155, 182, 45 },
                            VehicleId = new Guid("00000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 0, DateTimeKind.Utc),
                            RowVersion = new byte[] { 167, 175, 107, 144, 21, 210, 107, 65, 139, 116, 190, 117, 214, 255, 18, 88 },
                            VehicleId = new Guid("00000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = 4,
                            CityId = 1,
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 0, DateTimeKind.Utc),
                            RowVersion = new byte[] { 150, 200, 54, 15, 236, 87, 107, 70, 190, 43, 250, 55, 185, 234, 192, 95 },
                            VehicleId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = 5,
                            CityId = 1,
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 0, DateTimeKind.Utc),
                            RowVersion = new byte[] { 109, 28, 123, 220, 210, 179, 175, 73, 150, 158, 11, 64, 49, 106, 204, 124 },
                            VehicleId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = 6,
                            CityId = 1,
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 0, DateTimeKind.Utc),
                            RowVersion = new byte[] { 54, 29, 191, 129, 99, 149, 218, 78, 157, 125, 131, 182, 17, 27, 253, 154 },
                            VehicleId = new Guid("00000000-0000-0000-0000-000000000007")
                        });
                });

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.TaxRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("TaxRules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 0, DateTimeKind.Utc),
                            EndTime = new TimeSpan(0, 6, 30, 0, 0),
                            RowVersion = new byte[] { 211, 148, 148, 184, 97, 181, 186, 78, 137, 202, 212, 72, 141, 111, 179, 180 },
                            StartTime = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 0, DateTimeKind.Utc),
                            EndTime = new TimeSpan(0, 7, 0, 0, 0),
                            RowVersion = new byte[] { 108, 230, 210, 53, 21, 93, 198, 78, 165, 236, 188, 195, 228, 254, 215, 27 },
                            StartTime = new TimeSpan(0, 6, 30, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 0, DateTimeKind.Utc),
                            EndTime = new TimeSpan(0, 8, 0, 0, 0),
                            RowVersion = new byte[] { 242, 165, 29, 25, 178, 33, 33, 69, 150, 98, 235, 159, 116, 71, 38, 53 },
                            StartTime = new TimeSpan(0, 7, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.TollPassage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PassageTime")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PassageTime");

                    b.HasIndex("VehicleId");

                    b.HasIndex("CityId", "PassageTime");

                    b.ToTable("TollPassages", (string)null);
                });

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 0, DateTimeKind.Utc),
                            RegistrationNumber = "ABC123",
                            VehicleType = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 0, DateTimeKind.Utc),
                            RegistrationNumber = "DEF456",
                            VehicleType = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 0, DateTimeKind.Utc),
                            RegistrationNumber = "GHI789",
                            VehicleType = 4
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 0, DateTimeKind.Utc),
                            RegistrationNumber = "JKL012",
                            VehicleType = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 0, DateTimeKind.Utc),
                            RegistrationNumber = "MNO345",
                            VehicleType = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 0, DateTimeKind.Utc),
                            RegistrationNumber = "PQR678",
                            VehicleType = 5
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            CreatedOn = new DateTime(2025, 11, 2, 12, 32, 14, 0, DateTimeKind.Utc),
                            RegistrationNumber = "STU901",
                            VehicleType = 6
                        });
                });

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.City", b =>
                {
                    b.OwnsOne("CongestionTaxCalculator.Domain.ValueObjects.Money", "MaximumTaxPerDay", b1 =>
                        {
                            b1.Property<int>("CityId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("MaximumTaxPerDayAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("MaximumTaxPerDayCurrency");

                            b1.HasKey("CityId");

                            b1.ToTable("Cities");

                            b1.WithOwner()
                                .HasForeignKey("CityId");

                            b1.HasData(
                                new
                                {
                                    CityId = 1,
                                    Amount = 60m,
                                    Currency = "SEK"
                                });
                        });

                    b.Navigation("MaximumTaxPerDay")
                        .IsRequired();
                });

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.Holiday", b =>
                {
                    b.HasOne("CongestionTaxCalculator.Domain.Entities.City", null)
                        .WithMany("Holidays")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.TaxExemptVehicle", b =>
                {
                    b.HasOne("CongestionTaxCalculator.Domain.Entities.City", null)
                        .WithMany("TaxExemptVehicles")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CongestionTaxCalculator.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.TaxRule", b =>
                {
                    b.HasOne("CongestionTaxCalculator.Domain.Entities.City", null)
                        .WithMany("TaxRules")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("CongestionTaxCalculator.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<int>("TaxRuleId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("AmountValue");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("AmountCurrency");

                            b1.HasKey("TaxRuleId");

                            b1.ToTable("TaxRules");

                            b1.WithOwner()
                                .HasForeignKey("TaxRuleId");

                            b1.HasData(
                                new
                                {
                                    TaxRuleId = 1,
                                    Amount = 8m,
                                    Currency = "SEK"
                                },
                                new
                                {
                                    TaxRuleId = 2,
                                    Amount = 13m,
                                    Currency = "SEK"
                                },
                                new
                                {
                                    TaxRuleId = 3,
                                    Amount = 18m,
                                    Currency = "SEK"
                                });
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.TollPassage", b =>
                {
                    b.HasOne("CongestionTaxCalculator.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CongestionTaxCalculator.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CongestionTaxCalculator.Domain.ValueObjects.Money", "AppliedTax", b1 =>
                        {
                            b1.Property<Guid>("TollPassageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("AppliedTax_Amount");

                            b1.Property<string>("Currency")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("AppliedTax_Currency");

                            b1.HasKey("TollPassageId");

                            b1.ToTable("TollPassages");

                            b1.WithOwner()
                                .HasForeignKey("TollPassageId");
                        });

                    b.Navigation("AppliedTax");

                    b.Navigation("City");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.City", b =>
                {
                    b.Navigation("Holidays");

                    b.Navigation("TaxExemptVehicles");

                    b.Navigation("TaxRules");
                });
#pragma warning restore 612, 618
        }
    }
}
